### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [25]:
import numpy as np

vector = np.random.rand(10, 1)
print(vector)
print(vector.shape, '\n')

matrix = np.array([[11, 14, 17],
          [20, 23, 26],
          [29, 32, 35]])
print(matrix)
print(matrix.shape)

[[0.40645362]
 [0.01080909]
 [0.14936903]
 [0.82883161]
 [0.25352622]
 [0.40386475]
 [0.00700592]
 [0.19705675]
 [0.10886259]
 [0.74162632]]
(10, 1) 

[[11 14 17]
 [20 23 26]
 [29 32 35]]
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [45]:
print("1.", (vector + 10).round(2), '\n')
print("2.", matrix * 2, '\n')
new_vector = vector**2
print("3.", new_vector, '\n')

1. [[10.41]
 [10.01]
 [10.15]
 [10.83]
 [10.25]
 [10.4 ]
 [10.01]
 [10.2 ]
 [10.11]
 [10.74]] 

2. [[22 28 34]
 [40 46 52]
 [58 64 70]] 

3. [[1.65204544e-01]
 [1.16836423e-04]
 [2.23111081e-02]
 [6.86961830e-01]
 [6.42755421e-02]
 [1.63106733e-01]
 [4.90829242e-05]
 [3.88313618e-02]
 [1.18510636e-02]
 [5.50009603e-01]] 




### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [47]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [53]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [55]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [57]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [59]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [67]:
print(vector.T.shape)
print("Тепер вектор став вертикальним")

(1, 10)
Тепер вектор став вертикальним


In [81]:
print(vector)
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
print("Змінилась розмірність вектору, тепер він трьохмірний")

[[0.40645362]
 [0.01080909]
 [0.14936903]
 [0.82883161]
 [0.25352622]
 [0.40386475]
 [0.00700592]
 [0.19705675]
 [0.10886259]
 [0.74162632]]
[[[0.40645362]]

 [[0.01080909]]

 [[0.14936903]]

 [[0.82883161]]

 [[0.25352622]]

 [[0.40386475]]

 [[0.00700592]]

 [[0.19705675]]

 [[0.10886259]]

 [[0.74162632]]]
Змінилась розмірність вектору, тепер він трьохмірний


In [87]:
print(column_vector.T)
column_vector.shape

[[[0.40645362 0.01080909 0.14936903 0.82883161 0.25352622 0.40386475
   0.00700592 0.19705675 0.10886259 0.74162632]]]


(10, 1, 1)